name = "CINESOC Pack 1"
author = "Rat CEO"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e194f877b1141bbe1398586c9999122d6016f21ae9fe5a3d0a05d11cf85c994"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
