name = "CINESOC Pack 1"
author = "Rat CEO"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a726a3a67e8436594605327a432f4496fe0757517e00ee2ad182d56b1797cbec"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
